### ISSUE TITLE
Enforce testing coverage threshold(s)

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/open-block-explorer#102]
**Description**
Increase testing coverage to meet minimum threshold(s) & enforce for new PRs

**Minimum Initial Requirements**
- address any failing tests
- remove any/all instances of `/* istanbul ignore */` 
- 100% coverage for all vue component files in /components, /pages, /layouts
- minimal global coverage
 
**Running tests & coverage reports**
- run `yarn test` in root to run the test suite, this will also print out coverage & threshold stats, and generate istanbul report
- run `npx jest <filename/regex>` to run an individual test file 
- open `open-block-explorer/test/jest/coverage/lcov-report/index.html` in broswer to view static istanbul report page (useful for identifying uncovered code)

**Comment by karynemayer** [comment]
Close this issue to be addressed each time we add new unit tests
