### ISSUE TITLE
BUG - Transactions table design not implemented completely

### ISSUE THREAD

**Issue by ramijames** [telosnetwork/open-block-explorer#137]
As implemented:
<img width="1795" alt="image" src="https://user-images.githubusercontent.com/814302/161750499-811f5c59-9930-4aa8-95eb-6045185d9a89.png">

As designed:
<img width="1681" alt="image" src="https://user-images.githubusercontent.com/814302/161750462-7c773cf4-cc5c-4d12-b61d-c93c4a5588b3.png">

Missing:
- Colored memo
- Colored action

I deeply dislike the expand functionality you guys added. It looks weird and works weird. It also feels unnecessary.

**Comment by DonaldPeat** [comment]
@ramijames can you confirm this issue has been addressed?

**Comment by WikusKriek** [comment]
@donnyquixotic this is done.

**Comment by Kersten-TCD** [comment]
@ramijames can you please verify so we can close this issue?
