### ISSUE TITLE
BUG - Resource crunch colors

### ISSUE THREAD

**Issue by ramijames** [telosnetwork/open-block-explorer#139]
This wasn't well defined, but in the original designs, as resources reach their max, the color should change. I'm open to suggestion how to tackle this, but I think that anything above 80% should be red.

<img width="220" alt="image" src="https://user-images.githubusercontent.com/814302/161751812-8cd89628-b746-44ce-9ab5-207d9beb4ab3.png">

**Comment by ramijames** [comment]
![image](https://user-images.githubusercontent.com/814302/161751873-1926cdbc-e15b-4c3a-9502-4ec0ba1f5a4d.png)

**Comment by DonaldPeat** [comment]
@WikusKriek _anything above 80% should be red_
