### ISSUE TITLE
BP - Homepage BP world view

### ISSUE THREAD

**Issue by ramijames** [telosnetwork/open-block-explorer#140]
As this is the highest level view of the BPs on Telos, we'll start here.

![image](https://user-images.githubusercontent.com/814302/161777520-7d1c748b-f74e-402c-896a-25f46ade5b48.png)

## Map
You be showing a world map littered with BPs from across the network. I assume that showing all the active BPs (including standby position) will be slow and cumbersome. This should only include BPs in the top-21. Each BP is supposed to include their location in their BP.json, so we should use that as the source of data.

## Single BP
Each dot represents a BP. When you hover you can see either it is producing or not.
![image](https://user-images.githubusercontent.com/814302/161778398-e425a526-3f09-44e9-878f-7ee10db8a731.png)
![image](https://user-images.githubusercontent.com/814302/161778448-04ae980d-622f-4a0d-99dc-db916e68b9a9.png)

Clicking on the bubble should direct the user to that BP's account within the block explorer.

## Informational
On the right hand side there is a column with three metrics about the network:
- Head block
- Number of accounts
- Average TPS. 
 
This doesn't need to be constantly updating, but it sure would be nice :)

**Comment by Kersten-TCD** [comment]
code for most recent data / live data to be implemented.
