### ISSUE TITLE
BP - Add back missing main navigation

### ISSUE THREAD

**Issue by ramijames** [telosnetwork/open-block-explorer#141]
Now that we have some of the app blocked out, it is time to bring the nav back. It looks weird and awkward as it stands.

![image](https://user-images.githubusercontent.com/814302/161779633-3cb02c63-18b2-4fae-8fad-0e46e5274d96.png)

- There should be a Network link that acts as the "home" button back to /
- If the user has an account connected, there should be a Wallet link that brings them to the account selected in the connect dropdown. If not, this link should be hidden.
- There should be a link to the BP list.

**Comment by WikusKriek** [comment]
@donnyquixotic this is done.
