### ISSUE TITLE
BUG - Make Single View Multi-sig Proposal Hero Section Smaller

### ISSUE THREAD

**Issue by eosiodetroit-adam** [telosnetwork/open-block-explorer#199]
The hero section of the single multi-sig proposal view takes up too much room on desktop and mobile. There should only be ~1 inch of padding on the top and bottom of the heading/action buttons so that the space usage is optimized.

**Screenshots**
<img width="1667" alt="Screen Shot 2022-06-27 at 10 18 51 AM" src="https://user-images.githubusercontent.com/87721215/175963689-21c50ba1-8bcf-43bd-b8c1-8fb3411a9283.png">

**Desktop details:**
All browsers and operating systems.

**Smartphone details:**
All browsers and operating systems.

**Comment by karynemayer** [comment]
fixed with https://github.com/telosnetwork/open-block-explorer/pull/226
