### ISSUE TITLE
BUG - Single Multi-sig Proposal Page Does Not Show Proposal Details

### ISSUE THREAD

**Issue by eosiodetroit-adam** [telosnetwork/open-block-explorer#200]
The transaction area on the single multi-sig proposal view does not show the information about what the multi-sig does, only the information of the last action/transaction to interact with multi-sig proposal.

For example: https://explorer.telos.net/proposal/rfptreasury

The page currently shows the transaction of the last person to sign the msig and the trace information, but no the actual information of the proposal itself.

**Expected behavior**
The page should contain information about the actual proposal transaction instead of the transactions approving the proposal. The link to the transaction should go to the proposal transaction and not the approval transactions.

**Screenshots**
<img width="1667" alt="Screen Shot 2022-06-27 at 10 40 41 AM" src="https://user-images.githubusercontent.com/87721215/175968350-bde88e18-ac65-4574-a648-2927eb883f89.png">

**Desktop details:**
All operating systems and browsers.

**Smartphone details:**
All operating systems and browsers.

**Comment by karynemayer** [comment]
fixed with https://github.com/telosnetwork/open-block-explorer/pull/226
