### ISSUE TITLE
BUG - type ahead results don't render if last char is a period on re-type

### ISSUE THREAD

**Issue by DonaldPeat** [telosnetwork/open-block-explorer#204]
**Describe the bug**
If last char in searchbar query is a period '.', search results are not rendered in dropdown on re-type

**To Reproduce**
1. Type in search bar 'eosio.'
2. See results in dropdown
3. backspace to remove period
4. re-type period
5. see no results

**Expected behavior**
Should handle period as last char for search query and return results regardless of sequential typing

**Screenshots**
![image](https://user-images.githubusercontent.com/6848910/175997910-f4bdb18c-8c70-4507-a9db-4867be57183d.png)
![image](https://user-images.githubusercontent.com/6848910/176000213-74d1f41e-6c66-4952-9ed2-f43637368611.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome/Brave (presumably all)

**Comment by WikusKriek** [comment]
![image](https://user-images.githubusercontent.com/41372145/178003954-8771e2a1-97ad-4638-ad5b-64a6c0af979b.png)
![image](https://user-images.githubusercontent.com/41372145/178004053-8f406162-5448-44f5-a538-22a48f76a8f5.png)
Fails on mainnet but working on testnet.
@DonaldPeat @poplexity any idea whats causing this.

**Comment by WikusKriek** [comment]
Seems to have fixed this somehow in one of the other search chages. Does not appear to be a problem anymore @DonaldPeat
