### ISSUE TITLE
BUG - voting error

### ISSUE THREAD

**Issue by DonaldPeat** [telosnetwork/open-block-explorer#211]
**Describe the bug**
error when attempting to vote 

**Screenshots**
![image](https://user-images.githubusercontent.com/6848910/176762067-616460a8-dbd9-4657-b185-fcf7c3f5ab08.png)

**Additional context**
It references to owner permission though logged in with active and keys are also active

**Comment by WikusKriek** [comment]
This should already be fixed in [src/store/account/actions.ts](https://github.com/telosnetwork/open-block-explorer/pull/227/commits/a8df84ea30d3d9f4269f5b65ff843e51b2aaeecd)
