### ISSUE TITLE
BUG - creation account missing for accounts created via free account page

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/open-block-explorer#215]
**Describe the bug**
Accounts created via https://www.telos.net/signup do not display creation account on account page

**To Reproduce**
1. Go to https://explorer.telos.net/account/telostest222
2. see missing creator account in 'CREATED BY ...' sub text under account name

**Expected behavior**
should display the creator account

**Screenshots**
![image](https://user-images.githubusercontent.com/6848910/177200439-4add58c2-0631-4746-9faf-a4723aaa3e2e.png)

Additional Notes:
Likely related to #216

**Comment by WikusKriek** [comment]
@donnyquixotic this seems to be fixed.
