### ISSUE TITLE
BUG - inaccurate creation date for accounts created via free account page

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/open-block-explorer#216]
**Describe the bug**
<time> ago sub text under account shows inaccurate time stamp (4 years ago) for accounts created via https://www.telos.net/signup

**To Reproduce**
1. Go to https://explorer.telos.net/account/telostest222 (account created Jul 4th, 2022, or create a new account via https://www.telos.net/signup)
2. see 'created ... 4 years ago' sub text 

**Expected behavior**
should display accurate creation timestamp

**Screenshots**
![image](https://user-images.githubusercontent.com/6848910/177200224-c3c32069-6a22-459e-a9be-4a457724ea93.png)

Additional Notes:
likely related to #215

**Comment by WikusKriek** [comment]
@donnyquixotic this seems fixed?
