### ISSUE TITLE
Bug - default account permissions

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/open-block-explorer#244]
**Description**
account permissions used on login should be set and used for signing transactions. currently, signing tx defaults to 'active' whether or not a user is signed in as 'owner'. This can cause unintended tx failures if 'active' status doesn't have permission to sign tx.

**Describe the solution you'd like**
Default to same permissions on login ('owner'/'active') when signing transactions.

**Comment by karynemayer** [comment]
Closing this because if you sign in with owner and it requires active, Anchor does it seamlessly for you and asks for the active permission.

**Comment by donnyquixotic** [comment]
@karynemayer re-opened as bug with clarification.
