### ISSUE TITLE
BUG - proposal search should display proposal status and info 

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/open-block-explorer#245]
**Describe the bug**
clicking on a previously resolved proposal redirects to general (all) proposals page

**Expected behavior**
Should display the proposal with results and status

**Comment by karynemayer** [comment]
@donnyquixotic I have created the [prhsdy3ke4uv](https://explorer-test.telos.net/proposal/prhsdy3ke4uv). I cancelled it and created another one with the same name.
The url seems to be working and redirecting to the last one created 🤔 
Should we consider this a fixed issue or am I missing some reproducing steps?

**Comment by donnyquixotic** [comment]
@karynemayer yup, this is resolved.
