### ISSUE TITLE
BUG - search results not redirecting to the correct page

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/open-block-explorer#246]
**Describe the bug**
if duplicate accounts for proposals and accounts they should redirect to the appropriate page

 **Steps to Reproduce**

1. create proposal with same name as an existing account
2. select proposals tab
3. click on created proposal
4. search for same name in search bar (while on proposal page)
5. click on the result under 'accounts'
6. see reload/re-direct to proposal page instead of accounts page 

**Expected Behavior**
if a proposal has the same name as an existing account, when searching for that name, the account search result should re-direct to the account page, and proposal search result should load proposal page

**Additional context**
possibly related to #245

**Comment by karynemayer** [comment]
@donnyquixotic could you provide steps to reproduce or some screenshots?

**Comment by donnyquixotic** [comment]
@karynemayer this _may_ not be a bug anymore (?). I've added steps to reproduce.
