### ISSUE TITLE
BUG - Canceled msig proposals are not displayed

### ISSUE THREAD

**Issue by DouglasHorn** [telosnetwork/open-block-explorer#260]
**Describe the bug**
When trying to access the msig proposal after it has been canceled, it cannot be found when its link is clicked.

**To Reproduce**
1. Go to https://explorer.telos.net/proposal?tab=allProposal
2. Click on the Proposal Name "incr.maxinln"  (https://explorer.telos.net/proposal/incr.maxinln)
3. See error "Proposal not found"

**Expected behavior**
The proposal would be found.

**Additional context**

**Comment by karynemayer** [comment]
Fixed by #281
