### ISSUE TITLE
BUG - REX lend & withdraw failing

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/open-block-explorer#299]
**Describe the bug**
lend and withdraw actions in REX timeout and fail

**To Reproduce**
1. Login with an account that has liquid TLOS
2. Click on rex tab
3. lend or withdraw
4. See timeout notification/error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/6848910/185704540-1c69811b-86e6-4357-a7b1-ad02e751c7fd.png)

**Additional context**
- using Anchor

**Comment by WikusKriek** [comment]
Tested this on testnet and it worked fine for me.

**Comment by WikusKriek** [comment]
![image](https://user-images.githubusercontent.com/41372145/185791082-920c22d5-a157-43e7-8f29-ced53a6bafbc.png)
