### ISSUE TITLE
[Question] - Design / Features / Objective

### ISSUE THREAD

**Issue by HexBlit** [telosnetwork/open-block-explorer#3]
Apologize if this is described somewhere, but I want to help make this a reality as I have some bandwidth in January to help out.

- Is there a design mock-up for what the OBE should look like in the end? ( is the goal to make telos.bloks.io like clone?)  
- (Similarly, I assume colors/fonts/etc would be based on telos.net, but there is no Branding guide or at least not one I can easily find)
- Is there a board like Trello or using the Github projects page for feature development that we as contributors can help with? 
-  In the same vein, what features need to be done vs nice to have etc. 

Happy to help contribute in any way I can with the above too! 

With the goal of getting this out by end of February, I wanted to help ensure success as I am passionate about this project and Telos as a whole.

**Comment by DonaldPeat** [comment]
Correct, at the moment the project only contains scaffolding/boilerplate/config and some examples. The explorer will not be an exact clone of bloks but will certainly share common features and design where desired & appropriate. We have a dedicated team actively defining those features & design.  I will update the project with resources & links as they become publicly available.
