### ISSUE TITLE
Feature Request - allow populating amount input(s) on balance click

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/open-block-explorer#300]
For forms with amount inputs where a balance is displayed, balance should be clickable to populate the input field with the max value

example in REX:
![image](https://user-images.githubusercontent.com/6848910/185705485-5706f9b0-34ea-4bc7-895f-39066673d8a8.png)

**Additional context**
- could additionally add a tooltip (if there is already tooltip support) that explains this on hover (see teloscan /staking for example)
- may have to subtract the gas from max for successful transactions

**Comment by WikusKriek** [comment]
@donnyquixotic will it be enough to just make the max amount to enter MAX_liquid - 0.1 TLOS? Since gas is something like 0.01 TLOS.

**Comment by donnyquixotic** [comment]
Yea, I think that's fine
