### ISSUE TITLE
Feature Request - REX updates

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/open-block-explorer#308]
language updates

- [x] remove T-rex image 
- [x] change title 'Rex' -> 'Staking'
- [x] on account view, change current 'Staking' button to 'Resources' (cpu/net)
- [x] change 'Rex' button to 'Staking'
- [x] 'total tlos in rex' -> 'total TLOS staked'
- [x] 'matured rex' -> 'matured staked' (?)
- [x] 'maturing rex' -> 'maturing staked' (?)
- [x] 'rex savings' -> 'staked savings'
- [x] 'processing' tab -> 'staking'

new feature

- [x] add action to send 'Rex' to Savings 
- [x] add tab 'Savings'
- [x] add input and button to call action to send to savings (similar to current lend/unlend
- [ ] implement calculation for and display APY/APR (above general stats box)

Note: update web wallet to reflect same language

**Comment by Kersten-TCD** [comment]
@WikusKriek @donnyquixotic @poplexity 

I would propose to rename REX to "Staking (REX)" for iteration one. This will allow users to associate this with the learned term REX for the time being.

Please verify if this is possible for all above terms based on designs.

**Comment by WikusKriek** [comment]
> @WikusKriek @donnyquixotic @poplexity
> 
> I would propose to rename REX to "Staking (REX)" for iteration one. This will allow users to associate this with the learned term REX for the time being.
> 
> Please verify if this is possible for all above terms based on designs.

@Kersten-TCD Yes definitely, I think if we for now just include it at the top level(the button that launches the REX/Staking modal) it should be fine. Not necessarily on all the terms inside the modal. The user will then know that everything they do on the modal is REX related.
