### ISSUE TITLE
 Resources / Staking are now mixed up.

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/open-block-explorer#329]
@WikusKriek please verify changes. Resources / Staking are now mixed up.

![Bildschirmfoto 2022-09-12 um 17 12 30](https://user-images.githubusercontent.com/39388424/189691030-26f58db9-bdf6-4907-b20d-4f7233ae9eb6.png)

Staking (center button) must be "Resources" or "Resource Management"

![Bildschirmfoto 2022-09-12 um 17 12 36](https://user-images.githubusercontent.com/39388424/189691349-709302a6-4843-436a-8e4b-bca4d5ab92bf.png)

Ressource Management Header to be renamed.
Staked to CPU, Staked to NET and Staked by Others might be good to rename.

![Bildschirmfoto 2022-09-12 um 17 12 41](https://user-images.githubusercontent.com/39388424/189691628-653ca32a-c788-4a1d-856d-c772f19d0da1.png)

Lend: is this being used at all, we might want to remove @poplexity @donnyquixotic 
Lend CPU/NET: please move to resource management
Savings:  please move right side of staking (seems more logic)

_Originally posted by @Kersten-TCD in https://github.com/telosnetwork/open-block-explorer/issues/323#issuecomment-1243898153_

**Comment by WikusKriek** [comment]
@donnyquixotic resources button was renamed correctly with the PR for the ram changes. However I do not see the REX changes on the live branch. With everything merged we should end up with it all named correctly.

So on the rex changes PR it seems off but together with the RAM feature PR it all should be good.

**Comment by WikusKriek** [comment]
@donnyquixotic no worries I will make a new PR with the rex updates branch and it should then all look fine.
