### ISSUE TITLE
Vote - Displays Available TLOS?

### ISSUE THREAD

**Issue by telos-justin** [telosnetwork/open-block-explorer#369]

**Comment by telos-justin** [comment]
The vote page https://explorer.telos.net/vote shows 'Your Available TLOS'  -  This is not a relevant piece of information for this page. Maybe this should show the users Voteable TLOS  (ie amount of TLOS that is staked and therefor ready to use for voting)

**Comment by donnyquixotic** [comment]
Closing this as resolved, number displayed ('YOUR AVAILABLE VOTING TLOS') is pulled from account `voter_info.staked` (not total TLOS)
