### ISSUE TITLE
Bug - Proposal name case validation

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/open-block-explorer#389]
**Description**
Creating a proposal with mixed character case is rendered in lowercase

**Desired solution**
retain entered character/mixed case, or convert to lowercase on input blur to match search case

**Additional Info**
feedback via @Kersten-TCD 

possibly captured in more detail by https://github.com/telosnetwork/open-block-explorer/issues/386

**Comment by karynemayer** [comment]
I'm closing this because its a duplicate from #386
