### ISSUE TITLE
On the account page, the ability to filter tokens

### ISSUE THREAD

**Issue by poplexity** [telosnetwork/open-block-explorer#395]
The ability to generate a URL to an account's balance of a specific token or tokens.  Right now you can navigate directly to the tokens page, but this request is to also be able to filter by code/contract account or symbol.

https://explorer.telos.net/account/foflexitytls?tab=tokens

Would become for TLOS:

https://explorer.telos.net/account/foflexitytls?tab=tokens&code=eosio.token&symbol=TLOS
https://explorer.telos.net/account/foflexitytls?tab=tokens&code=eosio.token,proxibotstkn&symbol=TLOS,ROBO

These values are treated as `and` conditions, meaning they all must match.  URL could specify `code` and/or `symbol` and either one could be comma separated values in which case the values are `or` conditions, might need to review how this would work in practice with multiple values.

**Comment by karynemayer** [comment]
@poplexity what would be the design of this page? What is the content that we should show besides the balance?
