### ISSUE TITLE
Can't unstake `1 TLOS` even when funds are available

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/open-block-explorer#419]
## Overview

A misleading message indicates that you can't unstake 1 TLOS despite having enough available. We should prevent the user from inserting an invalid amount.

## Steps to reproduce

1. Make sure you have an account with TLOS Staked and available for unstaking
2. Go to account
3. Click on `Staking REX`
4. Click on the `Unstake` tab
5. Insert `1` for Matured TLOS

## Current behavior

An error message indicating that you have insufficient funds appears despite having `5.0362 TLOS` available.

![](https://user-images.githubusercontent.com/2939354/200994355-992d0b9c-82f8-4de0-91eb-c35576566870.png)

## Expected behavior

The user should not be allowed to insert less than the minimum amount.
If not possible, make sure the user is aware of what the minimal amount is.

**Comment by WikusKriek** [comment]
I can't reproduce this.
