### ISSUE TITLE
Same transaction is shown differently

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/open-block-explorer#439]
## Overview

Duplicated transactions in a msig are showed as one transaction in the sending address.

## Steps to reproduce

1. Go to create new proposal page
2. Select batch transfer
3. Add the same transaction twice on the csv: use the same sender, receiver, amount and memo
4. Create, approve and execute the proposal

## Current behavior

At the sending account history, only a single transaction is shown.

![](https://user-images.githubusercontent.com/39388424/200871607-660d2631-75ff-4507-973f-c6c5de6f54f3.jpeg)

## Expected behavior

At the receiving account history, both transactions appear. Both transactions should appear on both transaction histories. 
![](https://user-images.githubusercontent.com/39388424/200871602-b1c5d58d-68f5-4e63-92bc-724e50aaad15.jpeg)

**Comment by jaegerfe** [comment]
I just tested a batch of 15 transactions and I saw no issues.

On sender account (https://explorer-test.telos.net/account/entaojaegerr):
![image](https://user-images.githubusercontent.com/4021973/214424904-250ea455-d00f-4974-8b00-2588c3157ad5.png)

On receiver account (https://explorer-test.telos.net/account/hyogasereiou):
![image](https://user-images.githubusercontent.com/4021973/214425327-19f24bac-8dc9-42e3-acf2-8a5e6fe85a36.png)

Transaction link: https://explorer-test.telos.net/transaction/58070a19833b679f334592934314819e583cd7b778d8a34b5a8396c3ebd58c6c

**Comment by karynemayer** [comment]
Pagination is affecting this issue, so we'll hold on until the pagination refactor is done and double-check this again

**Comment by Viterbo** [comment]
Follow [this PR](https://github.com/telosnetwork/open-block-explorer/pull/561) for the pagination refactor or just use it directly here: https://deploy-preview-561--obe-staging.netlify.app/

**Comment by karynemayer** [comment]
Fixed
