### ISSUE TITLE
BUG - Staked by others missing precision on Account Page

### ISSUE THREAD

**Issue by DestinyDevTeam** [telosnetwork/open-block-explorer#44]
**Describe the bug**
Staked by others missing precision on Account Page

**To Reproduce**
1. Search for doublewabbit
2. Look at Staked by others

**Expected behavior**
Should render as 40.0000 and not 400000

**Comment by DonaldPeat** [comment]
@DestinyDevTeam   Please review and confirm fix. [PR](https://github.com/telosnetwork/open-block-explorer/pull/56  ) deployed here: https://app.netlify.com/sites/open-block-explorer-dev/deploys/6216ef1914c0a50008496ff5 Thanks.

**Comment by DestinyDevTeam** [comment]
Value is now showing correct.
![image](https://user-images.githubusercontent.com/74211870/155506177-4eeb2da1-2e7c-48f0-82f1-783ed74c91dd.png)

Precision 2/4 TBD. Consistency across all numeral values on the same page / site.

**Comment by DestinyDevTeam** [comment]
Tested OK at https://deploy-preview-56--open-block-explorer-dev.netlify.app/
