### ISSUE TITLE
BUG - Incorrect Resource Data on Account Page

### ISSUE THREAD

**Issue by DestinyDevTeam** [telosnetwork/open-block-explorer#45]
**Describe the bug**
Incorrect Resource Data on Account Page

**To Reproduce**
1. Search for 5abuetdetaci
2. Resources show %

**Expected behavior**
Expected CPU and NET 0% vs %
Expected RAM 36.5857%

Equation Used:

ram_usage: 2996 / ( ram_bytes: 8189 / 100 )

**Comment by DonaldPeat** [comment]
@DestinyDevTeam see linked pull request for netlify _deploy preview_ link.

**Comment by DestinyDevTeam** [comment]
Resources are now showing up correctly.

![image](https://user-images.githubusercontent.com/74211870/155696779-08f233e9-7dd2-4434-ac02-4b5bc9054871.png)
