### ISSUE TITLE
Feature Request - Labeling on Account Page

### ISSUE THREAD

**Issue by DestinyDevTeam** [telosnetwork/open-block-explorer#46]
Labeling on Account Page.

![image](https://user-images.githubusercontent.com/74211870/155377528-0029b02b-ba39-4737-8320-cdfef1d9b902.png)

- Total <- Available
- Staked by others <- Split in Staked Types

**Comment by DonaldPeat** [comment]
@DestinyDevTeam see linked pull request for netlify _deploy preview_ link.

**Comment by DestinyDevTeam** [comment]
Split In Staked Types was a request to split the Sum of Stakes by Self / Staked by Others.
Suggested Label: Total Staked, until we split.

Other Labels fine by me.

![image](https://user-images.githubusercontent.com/74211870/155697371-51a7a2bf-6174-4cfc-9ed7-50b3efb3bc31.png)

**Comment by DestinyDevTeam** [comment]
All Labels looking good.
![image](https://user-images.githubusercontent.com/74211870/156163681-d7d5c735-2417-4ff2-8373-62f850900506.png)
