### ISSUE TITLE
BUG - HTTP 500 on get_creator

### ISSUE THREAD

**Issue by DestinyDevTeam** [telosnetwork/open-block-explorer#47]
**Describe the bug**
Console Bug when Navigating to Account Page: HTTP 500 on get_creator

**To Reproduce**
1. Search Any Account
2. Open Developer Consoler
3. Look at Response for get_credator call

**Expected behavior**
Creation Details for the Telos Account

`{"statusCode":500,"error":"Internal Server Error","message":"account creation not found"}`

**Comment by DestinyDevTeam** [comment]
Seems to work for certain accounts like: eosmechanics

**Comment by DonaldPeat** [comment]
@DestinyDevTeam see linked pull request for netlify _deploy preview_ link. See description & notes on PR regarding this error.

**Comment by DestinyDevTeam** [comment]
Outside the scope of OBE as it seems to be related to Nodes.

![image](https://user-images.githubusercontent.com/74211870/155697686-fca4fa51-0ca4-4b2d-9ef4-6030ac23d955.png)
