### ISSUE TITLE
Mainnet should be the default option for `cleos`

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/open-block-explorer#474]
## Overview

`cleos` should always point to the chain that is being currently used.

## Steps to reproduce

1. Sign in with `cleos` on [OBE](https://explorer.telos.net/)

## Current behavior

See it pointing to testnet

## Expected behavior

Should require only mainnet account

**Comment by donnyquixotic** [comment]
@karynemayer I'm not able to re-create, do you want to re-purpose this to validate that the account name is valid?

**Comment by karynemayer** [comment]
I was also unable to reproduce it, so we should close this for now.
