### ISSUE TITLE
BUG - Console Error on Accounts with . in address

### ISSUE THREAD

**Issue by DestinyDevTeam** [telosnetwork/open-block-explorer#48]
**Describe the bug**
Console Error on Accounts with . address

**To Reproduce**
1. Search for auctns.dstny
2. Open Developer Console

**Expected behavior**
Staked by others should contain data

`TypeError: Cannot read properties of null (reading 'staked')
    at Proxy.<anonymous> (75.92e26e8a.js:1:7729)
    at Generator.next (<anonymous>)
    at s (75.92e26e8a.js:1:6994)`

**Comment by DonaldPeat** [comment]
@DestinyDevTeam see linked PR

**Comment by DestinyDevTeam** [comment]
Searching OK.
Account Missing . on Card:
![image](https://user-images.githubusercontent.com/74211870/156163881-86576771-ea4e-4f29-8516-c50e278d27b4.png)

**Comment by DestinyDevTeam** [comment]
Showing correct now.

![image](https://user-images.githubusercontent.com/74211870/156533358-f73cbf40-1724-4607-b57f-773de8d9242c.png)
