### ISSUE TITLE
Collapse/Expand multiple transfers within msig

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/open-block-explorer#487]
**Description** 
For transactions with multiple actions, there is currently a collapsible row under which those actions are visible. All actions  should instead be shown on their own row rather than hidden in a collapsible section.

**Screenshots**
![image](https://user-images.githubusercontent.com/6848910/207916565-7d8061ec-f621-4091-8771-98b5642fe212.png)

**Comment by karynemayer** [comment]
@karynemayer is this still an issue?

**Comment by Kersten-TCD** [comment]
@karynemayer yes, transactions for treasury.tcd still look the same.
