### ISSUE TITLE
form validation for staking resources

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/open-block-explorer#488]
**Description**
Transaction fails unless you stake a nonzero amount to _both_ cpu and net

**Reproduction Steps**
1. login to OBE and navigate to account page by clicking 'wallet'
2. click 'resources'
3. enter amount for one or the other resource inputs
4. see transaction failure

**Solution(s)**
- format tx data to accept nonzero value for one _or_ the other

**Screenshot**
![image](https://user-images.githubusercontent.com/6848910/208330479-f33c238f-050b-4c3e-b47e-922e8bbbd1c8.png)

**Comment by karynemayer** [comment]
@donnyquixotic does this still happens?
