### ISSUE TITLE
BUG - Sorting on Latest Transactions render Table sideways

### ISSUE THREAD

**Issue by DestinyDevTeam** [telosnetwork/open-block-explorer#49]
**Describe the bug**
Sorting on Latest Transactions render Table sideways

**To Reproduce**
1. Go to homepage
2. Sort on any column in the Transaction Table

**Expected behavior**
Same Data Size vertical/horizontal should not adjust column/row width/height

**Screenshots**
![image](https://user-images.githubusercontent.com/74211870/155379067-9b297186-86b2-45f0-a401-952320d6eba5.png)

![image](https://user-images.githubusercontent.com/74211870/155379155-4928f4c6-7c99-4c6d-b5b5-9e04faca4911.png)

**Comment by DonaldPeat** [comment]
@DestinyDevTeam see linked pull request for netlify Deploy Preview link

**Comment by DestinyDevTeam** [comment]
Columns are now Fixed to Content as Expected when sorting.
