### ISSUE TITLE
create proposal error

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/open-block-explorer#501]
**Description**
If user inputs invalid data, then corrects, errors persist preventing proposal creation.

**Reproduction Steps** 
- insert invalid data (such as not adding TLOS to the transfer amount)
- add TLOS
- error continues

**Solution**
auto-populate any available data to mitigate user error

**Screenshots**
![image](https://user-images.githubusercontent.com/6848910/211390096-81c0ceed-6f62-4b05-8464-ffce535b54fd.png)

**Notes**
- 500 `get_abi` error may be unrelated. If not, create an issue in https://github.com/telosnetwork/api-telos-net

**Comment by jaegerfe** [comment]
I tried to reproduce this issue:

1. Attempted to create a transfer proposal without the TLOS:
![image](https://user-images.githubusercontent.com/4021973/214368094-5b0d4976-d522-4820-beb4-2393dfc19532.png)
2. Inserted the TLOS on the quantity:
![image](https://user-images.githubusercontent.com/4021973/214368314-f21387bc-6154-4ed0-bf3e-8a1aefba9bb1.png)

Working as expected:
![image](https://user-images.githubusercontent.com/4021973/214368425-1fdb0c74-8a64-4a12-9e50-03def9a5783a.png)
![image](https://user-images.githubusercontent.com/4021973/214368496-0aae0735-60b9-427d-a1fe-582327059a5d.png)
