### ISSUE TITLE
BUG - Same as #48 but for Domain Accounts - Variation

### ISSUE THREAD

**Issue by DestinyDevTeam** [telosnetwork/open-block-explorer#51]
**Describe the bug**
Console Error on Domain Account Page

**To Reproduce**
1. Search for eosio
2. Open Developer Console

**Expected behavior**
Values in Detail Fields

`TypeError: Cannot read properties of null (reading 'ram_bytes')
    at Proxy.<anonymous> (/js/75.92e26e8a.js:1:7853)
    at Generator.next (<anonymous>)
    at s (/js/75.92e26e8a.js:1:6994)`

**Comment by DonaldPeat** [comment]
@DestinyDevTeam see linked PR

**Comment by DestinyDevTeam** [comment]
Working as Expected.
![image](https://user-images.githubusercontent.com/74211870/156164917-bd67dbd2-31d5-42f0-8b86-5763a7c58ed5.png)
