### ISSUE TITLE
BUG - Searching for Invalid TX Id - No Error Handling

### ISSUE THREAD

**Issue by DestinyDevTeam** [telosnetwork/open-block-explorer#52]
**Describe the bug**
Misleading Behaviour without Formatted Error Message - Human Readable

**To Reproduce**
1. Alter a valid TX Id
2. Search for the Invalid TX Id

`TypeError: Cannot read properties of undefined (reading 'map')
    at Proxy.<anonymous> (933.2d361609.js:1:3745)
    at Generator.next (<anonymous>)
    at i (933.2d361609.js:1:2556)`

![image](https://user-images.githubusercontent.com/74211870/155384097-8287d284-95eb-4f6b-90bf-440b2987dd23.png)

**Comment by DonaldPeat** [comment]
@DestinyDevTeam  see linked PR for netlify deploy preview link

**Comment by DestinyDevTeam** [comment]
Error Message shown if TX Id is not found / incorrect.
![image](https://user-images.githubusercontent.com/74211870/156165169-3922facb-54b9-4737-8c7d-c87c1c7bef6b.png)
