### ISSUE TITLE
Transaction error using cleos

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/open-block-explorer#526]
## Description
When you use cleos to do a transaction, it shows/leaves a "Transaction Failed:" dialog on the screen

**Notes**
feedback via @poplexity 

To reproduce:
- login to an account using cleos, eg. **montevideouy** with permission **active**
- go to the account page, eg. `/account/montevideouy`
- click **resources** button
- for any of the tabs in the Resources modal, fill out all of the fields (e.g. Add CPU/Net -> add 1 TLOS to CPU) and click **confirm**
- click **copy** in the modal that appears
- along with "Copied", a modal will appear saying "Transaction failed:"

## Tasks
- [ ] Change the copy button actions in order to not propagate the done event

**Comment by EJSG** [comment]
Note: PR https://github.com/telosnetwork/open-block-explorer/pull/559 missed several instances of this bug in the Staking tab. Issue is still WIP
