### ISSUE TITLE
BUG - Responsive Design on Account Page

### ISSUE THREAD

**Issue by DestinyDevTeam** [telosnetwork/open-block-explorer#53]
Missing Responsive Design on Account Page

- Known Issue

![image](https://user-images.githubusercontent.com/74211870/155384517-a9833a1d-d0ad-4657-b354-eed2ced4248c.png)

**Comment by DonaldPeat** [comment]
@DestinyDevTeam see linked PR for deploy link

**Comment by DestinyDevTeam** [comment]
Card not broken for different aspect ratios.
