### ISSUE TITLE
tx table filter search input tooltip

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/open-block-explorer#536]
**Description**
Better communicate what can be filtered in the transaction table

**Solution**
add info icon and tooltip that displays which fields can be currently filtered

#### Notes
Recommended to be addressed alongside https://github.com/telosnetwork/open-block-explorer/issues/509

**Comment by karynemayer** [comment]
Should be addressed alongside https://github.com/telosnetwork/open-block-explorer/issues/509
