### ISSUE TITLE
BUG - Broken Account Creation Link

### ISSUE THREAD

**Issue by DestinyDevTeam** [telosnetwork/open-block-explorer#54]
**Describe the bug**
Link to Account Creator is Broken

**To Reproduce**
1. Search for eosmechanics
2. Click on alohaeosprod

**Expected behavior**
`https://explorer-test.telos.net/account/alohaeosprod`

Erroneous Link:
`https://explorer-test.telos.net/account/account`

![image](https://user-images.githubusercontent.com/74211870/155385803-e4270324-089b-4017-af6d-18265e644d69.png)

**Comment by DonaldPeat** [comment]
@DestinyDevTeam see linked PR for netlify _Deploy Preview_ link.

**Comment by DonaldPeat** [comment]
![image](https://user-images.githubusercontent.com/6848910/155670960-2e19133a-cd3f-4d77-af2f-fc9baca2a7ee.png)

**Comment by DestinyDevTeam** [comment]
Link to created by is now working.
Did test all the way to root: eosio from an ordinary account.
