### ISSUE TITLE
Scoped search should consider all transactions

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/open-block-explorer#547]
## Overview
When applying the search and the filters that are scoped to the account's transaction, it only considers the current page.

## Steps to reproduce
1. Using the main search bar, select an account such as `tf` 
2. Try any filter
3. See it that only applies to the current page

## Acceptance criteria
* The selected filters should be applied to all transactions, providing a new list of pages containing only filtered transactions
* For better performance, consider grouping all filters and creating an `Apply Filters` button to start filtering the account's transaction.
* Latest transactions label should appear only once, i.e. remove the one below

**Comment by Viterbo** [comment]
We discussed with @donnyquixotic what to do with this issue in today's meeting and decided to remove all current filter buttons and instead add a group of new components that reflects the actual capabilities of the Hyperion API:
e.g:
- text search won't be present.
- token filter should be selectable from a list and not text input.
- Range of days will be pretty much the same as now but one that actually works XD
- add the capability to filter by account (e.g: in simple transfers the "from" and "to" accounts can be filtered this way)
