### ISSUE TITLE
Incorrect CPU/Net balance

### ISSUE THREAD

**Issue by EJSG** [telosnetwork/open-block-explorer#565]
## Description

For this account which has no CPU or NET balance, the balance is shown as `20` when it should be `0`
![Image](https://user-images.githubusercontent.com/11837820/217084928-8be7f3b3-151e-4810-9e89-a7220335f098.png)

**Comment by donnyquixotic** [comment]
@EJSG which account is this? I'm having issues reproducing

**Comment by EJSG** [comment]
@donnyquixotic sorry, on testnet its `eztestnet123`

**Comment by donnyquixotic** [comment]
closing as not a bug, (resources are delegated on testnet account creation)
