### ISSUE TITLE
make sure fuel do not break if the chain do not support the service (OBE)

### ISSUE THREAD

**Issue by Viterbo** [telosnetwork/open-block-explorer#582]
# Description

Some blockchain networks are incompatible with the service or their community expresses disinterest in using it. In either of these scenarios, the fuel service should neither be involved in the signing process nor break anything.

# Acceptance Criteria
Make the fuel implementation not break when the blockchain is not supported.

**Comment by donnyquixotic** [comment]
resolved by https://github.com/telosnetwork/open-block-explorer/pull/583#
