### ISSUE TITLE
Filtering makes pagination break in some pages

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/open-block-explorer#595]
## Overview
On the transactions tab, if you apply a filter and start navigating through the transactions pages, an error occurs and that page doesn't update the transactions anymore.

![Screen_Recording_2023-02-17_at_12_32_14_AdobeExpress](https://user-images.githubusercontent.com/2939354/219788257-c806b56d-ff27-45c2-a707-2eca56a92d11.gif)

## Acceptance criteria
* The pagination should show all transactions without a page breaking

**Comment by Viterbo** [comment]
@karynemayer, how are you doing?
I was not able to reproduce the problem.
Can you check if you can reproduce this Bug in the current dev branch?
The gif animation is too small and I can't read anything although I understand what's happening.

**Comment by karynemayer** [comment]
It has been fixed with pagination and filtering refactor
