### ISSUE TITLE
Pagination results change when moving through pages

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/open-block-explorer#612]
## Overview
The results are updated when you move through the pages.

Steps:

1. Go to transactions
2. Turn off live transactions
3. Note the first transaction
4. Move to the second page by clicking next
5. Move again to the first page by clicking prev
6. See the first transaction has changed

Note: see https://hyperion.docs.eosrio.io/api/v2/#v2historyget_actions `global_sequence`, may need to update param/return types

## Acceptance criteria
* When live transactions are off, the transactions should not be updated regardless of page navigation
* If the user goes to a very old page, the older transactions should be persisted

**Comment by Viterbo** [comment]
THe solution should use a range on the global_sequence parameter like this:

https://testnet.telos.net/v2/history/get_actions?sort=desc&skip=0&limit=10&global_sequence=0-284532688

This always returns the same range paginated by skip and limit
