### ISSUE TITLE
update UX icons 

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/open-block-explorer#620]
- header is distorted and both have a white (instead of transparent background)
![image](https://user-images.githubusercontent.com/6848910/221270785-b0ce364e-40a2-43e4-bf85-5b470425960d.png)

_Originally posted by @donnyquixotic in https://github.com/telosnetwork/open-block-explorer/pull/602#pullrequestreview-1314123604_

**Comment by jaegerfe** [comment]
Sounds like it's fixed. Could you retest it @donnyquixotic ?

**Comment by donnyquixotic** [comment]
resolved
