### ISSUE TITLE
'send' token filtering broken 

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/open-block-explorer#623]
##Overview
Tokens that you don't have on your balance are not listed on the send token, but TLOS is always the first option.

**Screenshots**
![image](https://user-images.githubusercontent.com/6848910/221385298-392cfbb4-dbb0-4a79-9df5-333ccf6839cb.png)

## Acceptance criteria
* Default to TLOS if they have a positive balance
* Force user to pick if they don't have TLOS

**Notes**
feedback via @ackza, cannot reproduce:
![image](https://user-images.githubusercontent.com/6848910/221385323-d3e1a554-7a63-4b8b-a3ab-95d7cffa3c3f.png)

**Comment by karynemayer** [comment]
Waiting for @ackza to make sure its fixed
