### ISSUE TITLE
Buy RAM is empty when account doesn't have funds

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/open-block-explorer#624]
## Overview
Buy RAM form looks empty with an account with no balance on it.

![Image](https://user-images.githubusercontent.com/2939354/221650892-4f33560b-44a7-40d5-a7a0-f3618d4ea96f.png)

## Acceptance criteria
The form should appear regardless

**Comment by EJSG** [comment]
@karynemayer are you still able to reproduce this? i cannot
