### ISSUE TITLE
Details of a transaction are wider than the table under the traces tab

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/open-block-explorer#678]
## Overview
The content of a transaction exceeds the size of the table column, as shown in the image below. 

![Screenshot 2023-03-28 at 15 44 14](https://user-images.githubusercontent.com/2939354/228386970-73c5231c-9b84-4b66-bbc5-80f9dcacc189.png)

The size error only happens when the data is expanded.

![Screenshot 2023-03-28 at 16 10 29](https://user-images.githubusercontent.com/2939354/228387096-a03983bb-1f81-498b-9cdf-26cf4e093e67.png)

The transaction in the images can be accessed by:
`transaction/168c07490f56895bddfba45261e6f5f03cfae0454e1488f87142ebf66cd4457c?tab=traces`

**Comment by kylanhurt** [comment]
@donnyquixotic Long text strings already seem to be wrapping to the next line. Maybe consider closing this one?

**Comment by donnyquixotic** [comment]
Resolved
