### ISSUE TITLE
Keys don't follow the selected account

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/open-block-explorer#679]
## Overview
Switching accounts with one of the tabs open (e.g. keys, as shown in the image) doesn't update the tab content. 

![Screenshot 2023-03-29 at 13 44 13](https://user-images.githubusercontent.com/2939354/228662978-633b2588-479e-4824-bff1-7ac11e50e687.png)

#### Steps
You're logged in with an account that is not `tf`.

1. Go to an account, such as `tf`
2. Select the `keys` tab 
3. Click on the `Wallet` tab to go to your wallet
4. Scroll down
5. See the `keys` permissions associated with the `tf` account instead of with your own

## Acceptance criteria
- The keys showed should always be referring to the selected account

**Comment by donnyquixotic** [comment]
resolved
