### ISSUE TITLE
Traces table sometimes cuts some of the text

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/open-block-explorer#681]
## Overview
The image below shows how the table under traces behaves with longer texts. 
![Screenshot 2023-03-29 at 14 03 44](https://user-images.githubusercontent.com/2939354/228667770-956b2589-38e1-4908-ad2e-497a0792b357.png)

## Acceptance criteria
The content of the transactions should always be fully shown.

**Comment by donnyquixotic** [comment]
resolved
