### ISSUE TITLE
Empty stake form for accounts with 0 balance

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/open-block-explorer#684]
## Overview
When you log in with an account that doesn't have any balance, and you go to the account's resources, the stake input doesn't appear. The images below show this happening both in mainnet & testnet.

![Screenshot 2023-03-30 at 15 20 11](https://user-images.githubusercontent.com/2939354/228976905-d336e16b-1409-418d-a2da-d44b7e809790.png)
![Screenshot 2023-03-30 at 15 21 11](https://user-images.githubusercontent.com/2939354/228976913-57d17fd2-e1f1-4738-a233-0bf32471ca69.png)

#### Steps
1. Sign in with an empty account

> Pro tip: sign in with `cleos` using the following accounts: `shiryufofao1` for testnet or `saorinhamala` for mainnet. 

2. Go to the account's wallet
3. Click on `Staking (REX)`
4. See that the form for staking doesn't appear like the unstaking one does.

**Comment by kylanhurt** [comment]
@karynemayer Are you still seeing this issue? I am not.

<img width="667" alt="image" src="https://github.com/telosnetwork/open-block-explorer/assets/6249205/551dc0dc-2dc9-40f7-be7f-93f7879f8506">

**Comment by donnyquixotic** [comment]
resolved
