### ISSUE TITLE
Using the search bar may break the UI and require page refresh

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/open-block-explorer#689]
## Overview
On OBE when you search for something it sometimes just yeets the search input and doesn’t display anything, requires a hard refresh to get the search input back. The example below shows the search for `EOS5wBnSMsfxJH9CvAVCowjuN4iAsE4KQXs9JYUKDR9WvxfGtRj9b`.

https://user-images.githubusercontent.com/2939354/231834248-8842c80d-3039-4c1f-be0d-10f927e02481.MP4

**Comment by donnyquixotic** [comment]
This results from searching for a bad key string, now displays 'key not found'
