### ISSUE TITLE
Transactionview - Actions - Live transactions option visible when viewing a transaction

### ISSUE THREAD

**Issue by pmjanus** [telosnetwork/open-block-explorer#693]
**Describe the bug**
Live transactions option visible when viewing a transaction, since there is no change to this data this option should not be visible here.

**To Reproduce**
1. go to https://explorer.telos.net/transaction/156e5201206075ca6dc75c84de4de83cae2d2969087f58913f2946fe8e35b4f3
2. view option

**Expected behavior**
The Live transactions option should be hidden as it has no effect on this view

**Screenshots**
<img width="1293" alt="image" src="https://user-images.githubusercontent.com/97489909/236321287-d8f62cd2-0f3a-4baf-a800-5d5e89785de1.png">

**Comment by donnyquixotic** [comment]
This is resolved (functionality removed when viewing a single transaction)
