### ISSUE TITLE
Transaction Failure on OBE when Interacting with Contract using Cleos: Invalid Name Error

### ISSUE THREAD

**Issue by pmjanus** [telosnetwork/open-block-explorer#695]
# Describe the bug
When trying to interact with a contract on OBE and logged in with cleos, clicking to push the transaction fails with an error message: "Transaction Failed: Error: Invalid name".

# To Reproduce

Log in to OBE with any account name
Go to the 'tf' account
Attempt to call 'startelect'
See error message: "Transaction Failed: Error: Invalid name"
Expected behavior
The transaction should be successfully pushed without any error messages.

**Comment by karynemayer** [comment]
Fixed by https://github.com/telosnetwork/open-block-explorer/pull/710
