### ISSUE TITLE
Remove maps from other chains

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/open-block-explorer#711]
## Overview

We should remove the map because its hardcoded for telos network, showing only the block producers for Telos. Also, other chains don't necessarily want it a map.

## Acceptance Criteria
- Include a configuration to a chain to define if the map should appear or not
- Set the configuration to `false` for every chain **except** telos and telos testnet.

**Comment by eosiodetroit-adam** [comment]
@karynemayer So this would be an item that needs to be made configurable?

**Comment by jaegerfe** [comment]
> @karynemayer So this would be an item that needs to be made configurable?

We already have the flag for map display on the chain config. On #747 I turned off the map for the other networks.
