### ISSUE TITLE
WALLET - Single Account template updates - main information section

### ISSUE THREAD

**Issue by ramijames** [telosnetwork/open-block-explorer#72]
To support the new connected account functionality, we'll be updating all the Single Account templates. 

For all accounts, except for ones that the user has attached, users will now see:

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/814302/156378970-419e994e-c38d-4421-b495-f610ea5028ae.png">

In the main informational section, this will show the user:

- accountname
- creator account
- status of the resources, with a nice circle graph around each
- a table of the account's balances for:
-- total
-- refunding tokens
-- staked by other accounts
-- staked to REX (for later, I think)

In the secondary detail section, we will have tabs with sub-content:

- Transactions
- Tokens
- Keys
- Children (child accounts created by this account)

## Transactions

Transactions will use the typical quasar table functionality already developed to show transactions.

<img width="1241" alt="image" src="https://user-images.githubusercontent.com/814302/156379585-2fabe010-b90e-42f4-abc8-f14ef085db9d.png">

## Tokens

Tokens will use the following layout:

<img width="1248" alt="image" src="https://user-images.githubusercontent.com/814302/156379729-74ecc00f-476b-413e-8ca4-982985c3d868.png">

## Keys

Keys and permissions will be shown using this layout:

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/814302/156379799-8561d3a6-174f-4a87-a4a2-1621b1aac030.png">

# Children

Children will be shown using a simple quasar table.

**Comment by DonaldPeat** [comment]
@ramijames @DestinyDevTeam I split this into two cards,  the main info section that this PR addresses, and another card with this linked for the secondary detail section.  See the Netlify Deploy Preview link in the associated PR to review. Thanks.
