### ISSUE TITLE
ETH/USD (ETH/USD) is at 1,827.40 (-3.13%)

### ISSUE THREAD

**Issue by u353y** [telosnetwork/open-block-explorer#721]
ETH/USD (ETH/USD) is at 1,827.40 (-3.13%)

http://www.investing.com/crypto/ethereum/eth-usd?utm_source=investing_app&utm_medium=share_link&utm_campaign=share_instrument

**Comment by u353y** [comment]
,u@my

**Comment by poplexity** [comment]
Please don't post irrelevant issues like this.
