### ISSUE TITLE
Can't move ALL to savings in REX

### ISSUE THREAD

**Issue by Viterbo** [telosnetwork/open-block-explorer#734]
**Describe the bug**
There are currently two bugs that prevent this "move to savings" from happening: One is described here and the other one is that if the amount you are moving to savings is the same as the max available (typically when you hit the button you are in that case) the button "Move to savings" is doing nothing.

The problem is in this line:
https://github.com/telosnetwork/open-block-explorer/blob/master/src/components/staking/SavingsTab.vue#L56
```typescript
        async function moveToSavings() {
            void store.dispatch('account/resetTransaction');
            if (
                toSavingAmount.value === '0' ||
                toSavingAmount.value === '' ||
                Number(toSavingAmount.value) >= eligibleStaked.value // <<<-- Here is the problem
            ) {
                return;
            }
            // ...
        }
```

**Comment by donnyquixotic** [comment]
resolved
