### ISSUE TITLE
Incorrect EOS vote counts 

### ISSUE THREAD

**Issue by eosiodetroit-adam** [telosnetwork/open-block-explorer#738]
**Describe the bug**
The vote counts for block producers are vastly overstated from the true amounts.  The total votes under the bar graph on the left side are also overstated.

**To Reproduce**
1. Go to the vote page of the EOS portion of OBE (or the url for the explorer.antelope.io EOS block explorer when it's live)
2. Look at the vote column in the list of BPs and under the bar graph showing network-wide voting information.

**Expected behavior**
The vote counts should match the real on-chain amounts.

**Additional context**
You can use https://eosauthority.com/?network=eos as a reference to cross check the amounts.

The ordering is correct, the counts are not.

**Comment by karynemayer** [comment]
After some investigation, we were able to verify that the amount of votes showing is correct. We show the total sum of votes. In the future, we might want to show the voting increase/decrease for a certain period of time.
