### ISSUE TITLE
Accounts should display which producers they have voted on.

### ISSUE THREAD

**Issue by pmjanus** [telosnetwork/open-block-explorer#751]
**Describe the Feature**
On OBE, it is not showing which producers an account voted for

**Expected behavior**
When looking at an account via the /account/:accountName route, you should be able to see which BPs the account has voted for.  The UX design for this is not strictly decided upon, but it should be done with consideration for what's important, and not dominate the main account page, while still being obvious where to find it without looking too much around the page.

**Solution**
- Add a tab 'votes' to the account page
- Add total number of validators voted for
- Display list of linked validator accounts

**Screenshots**
![image](https://github.com/telosnetwork/open-block-explorer/assets/6848910/c7d98de6-7260-417f-a632-7921b56b351a)

**Comment by poplexity** [comment]
The producers should show an array, maybe not as a JSON array... but as a more user friendly display maybe like tags would be (but ordered)?

This used to work I am 99% sure, so is a regression of some kind.

**Comment by kylanhurt** [comment]
@poplexity @pmjanus Which page is this supposed to be on?

**Comment by donnyquixotic** [comment]
@kylanhurt ping me about this one before you tackle it.

**Comment by donnyquixotic** [comment]
@kylanhurt see issue update
