### ISSUE TITLE
Can't sign an msig proposal with owner key

### ISSUE THREAD

**Issue by cuvialabs** [telosnetwork/open-block-explorer#752]
**Describe the bug**
Telos Explorer will not allow me to sign an msig updateauth proposal with an owner key.   It defaults the key back to active which results in an assertion error.

**To Reproduce**
1. Go to https://explorer-test.telos.net/proposal/updateactivf
2. This transaction should be called updateowner,  its updates the owner keys of bennyfitokent1
3. Even thought I'm logged in as key1bennyfi1@owner,  when I go to execute the transactions, it defaults to key1bennyfi1@active
resulting in an assertion error.   
5. I reported this to Anchor,  thinking it was their issue,  but here's their response.
"I spoke with our team regarding this and it turns out the issue resides with the block explorer. Regardless of the account/permission you sign in with to the block explorer, the explorer itself is forcing the msig “approval” to use the accounts active permission, so then when its routed to Anchor, it pops up the active permission.  You can checkout the code for the block explorer here - https://github.com/telosnetwork/open-block-explorer/blob/ac8ed50add1cf1557bce40b7596dd28d48c69539/src/pages/ProposalItem.vue#L355 

Anyhow, this is not something that we can repair on our end, so i would suggest reaching out to the Telos support team for their block explorer and see what they recommend as a solution,  We'll be reaching out as well, but the more people bring up the issue, the more they are likely to fix it.
If there's anything else we can help you with, please let us know."

**Expected behavior**
I log in as owner to approve a msig,  I need to be able to sign as owner.

**Screenshots**
![msig3](https://github.com/telosnetwork/open-block-explorer/assets/36161995/0c7b3d99-bd93-4024-b94a-1a988f51153a)
![msig1](https://github.com/telosnetwork/open-block-explorer/assets/36161995/d62ec46b-99fd-40bc-bb37-cd299146ef40)
![msigissue2signing](https://github.com/telosnetwork/open-block-explorer/assets/36161995/31f8bbb0-84ec-41c9-ace5-87e3f1e2b31e)
![msig4](https://github.com/telosnetwork/open-block-explorer/assets/36161995/4c1008b2-04d6-4ea8-b123-996d7f30aef6)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  windows
 - Browser [e.g. chrome, safari]  Brave

**Additional context**
We're hardening our treasury security with Ledger wallets.   We need to be able to add and remove owner keys to our system accounts.   We are using a similar account structure to Telos's eosio account.   Can you suggest a work around for this that will allow us to still use HW wallets?  How do you handle this on the eosio account?

**Comment by cuvialabs** [comment]
Any comment on this?

**Comment by donnyquixotic** [comment]
> Any comment on this?

@cuvialabs Please see my comment on #753, I believe I've resolved the issue

**Comment by cuvialabs** [comment]
Replied to #753,   same result.   Its defaulting to the active key,  when I'm logged in with the owner.

**Comment by cuvialabs** [comment]
Sorry to be a pain on this,   but its blocking our workflow.    Any update?   Did you push the new version with the fix?
