### ISSUE TITLE
Action info gets cropped when it has two lines of info

### ISSUE THREAD

**Issue by Viterbo** [telosnetwork/open-block-explorer#761]
**Describe the bug**
As can be seen in the screenshot, the height of the row is not enough to hold two lines of the info on each action.

**To Reproduce**
1. Go to [this account page](https://explorer.telos.net/account/viterbotelos)
3. Scroll down to see the last actions
4. See the error described. The info of the action does not fit in the height space.

**Expected behavior**
No cropping of the text is expected when it has exactly two lines.

**Screenshots**

![image](https://github.com/telosnetwork/open-block-explorer/assets/4420760/4ccfb1e5-c186-4977-8005-d7d573f508d5)

**Comment by kylanhurt** [comment]
So, for clarification, we want it to crop only after the 2nd row, right?

**Comment by donnyquixotic** [comment]
Resolved by #764
