### ISSUE TITLE
Add number separators (commas) for block numbers

### ISSUE THREAD

**Issue by kylanhurt** [telosnetwork/open-block-explorer#794]
**Describe the bug**
Without number / thousands separators it becomes more difficult to read block numbers. 

**To Reproduce**
Go to homepage

**Expected behavior**

**Screenshots**
![image](https://github.com/telosnetwork/open-block-explorer/assets/6249205/c027fbe7-ad05-4853-834e-08c6b163f54c)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by matthewdarwin** [comment]
Some languages use spaces, some use commas.  The choice of 1000s separator character should depend on browser config, not hard-coded value.

**Comment by kylanhurt** [comment]
@matthewdarwin Agreed. Current PR uses `toLocaleString()` which leaves it up to the browser.
