### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by reelhenrie** [telosnetwork/open-block-explorer#80]
Mobile view problem

**Comment by DonaldPeat** [comment]
Hi @reelhenrie! Could you please add more information to help us identify & fix the issue? You can reference the [bug issue template](https://github.com/telosnetwork/open-block-explorer/issues/new?assignees=&labels=bug&template=bug_report.md&title=BUG) for information we find useful. Thanks!

**Comment by roger-eosuk** [comment]
Same as 82

**Comment by DonaldPeat** [comment]
I'm assuming you mean #81
