### ISSUE TITLE
BUG - table on mobile

### ISSUE THREAD

**Issue by DonaldPeat** [telosnetwork/open-block-explorer#81]
**Describe the bug**
On mobile, timestamp and action columns overlap eachother 

**To Reproduce**
1. Navigate to  [https://explorer.telos.net](https://explorer.telos.net/) in phone browser
2. scroll down to transaction table to view 

**Expected behavior**
Timestamp & Action headers should not overlap. Timestamp column values should break instead of overlapping.

**Screenshots**
![image](https://user-images.githubusercontent.com/6848910/156826901-97c1bcd2-8bea-4930-958f-72a165ae966a.png)

**Smartphone (please complete the following information):**
 - Device: Samsung S20
 - Browser: Brave (Chrome) 

**Additional context**
Only in portrait mode

**Comment by DestinyDevTeam** [comment]
Ok on Samsung S9+ using Chrome.
![Screenshot_20220307-130248_Chrome](https://user-images.githubusercontent.com/74211870/157031262-03a26cb7-5c26-4c3c-8593-5261cd3b9e8f.jpg)
