### ISSUE TITLE
Format timestamp in tx table

### ISSUE THREAD

**Issue by DonaldPeat** [telosnetwork/open-block-explorer#83]
### Format timestamp value for all tables

- method to format date see [https://teloscan.io](https://teloscan.io) table for example
- add formatting method to 'Timestamp'  column definition

**Comment by DestinyDevTeam** [comment]
**Previous**
![image](https://user-images.githubusercontent.com/74211870/157031663-383e4929-015c-4954-963d-3a1520d7ce82.png)

**New**
![image](https://user-images.githubusercontent.com/74211870/157031686-9879f8c5-d9a2-43ab-81a5-73e0a5e04a13.png)

If this is the way we want to show it, I guess it is OK. But should be an option to see exact timestamp in UTC for transactions for cross checking table deltas and other usecases ?

**Comment by DonaldPeat** [comment]
this is very easy to toggle and format 'normally' i'll merge for now and can adjust after pending feedback
