### ISSUE TITLE
Create a Vibrant README

### ISSUE THREAD

**Issue by DonaldPeat** [telosnetwork/open-block-explorer#84]
### Create a Vibrant README ✏️  
suggestions per @chiedo  from issue #23 

We have lots of room to make the [Open Block Explorer README](https://github.com/telosnetwork/open-block-explorer) more inviting to open source developers. See the [next.js README](https://github.com/vercel/next.js) as an example.

1. Describe what Open Block Explorer is
1. Link out to a live example of the Open Block Explorer
1. Add a “contributing” guide which guide developers new to the project in the contribution process
2. Include Links to design docs if available
1. Link to some “good first issues” for developers new to the project
1. Describe who the core contributors are in the footer
1. Link out to the Open Block Explorer Discord and/or Telegram community

**Comment by Kersten-TCD** [comment]
Done in latest PR.
