### ISSUE TITLE
The msig action code appears truncated

### ISSUE THREAD

**Issue by Viterbo** [telosnetwork/open-block-explorer#840]
**Describe the bug**
The code appears truncated

**To Reproduce**
1. Go to [this link](https://explorer.telos.net/proposal/voqbcbtcll3j)
3. Expand action tab

**Expected behavior**
The code should be complete and not truncated

**Screenshots**
![image](https://github.com/telosnetwork/open-block-explorer/assets/4420760/f38141e3-e0cd-4aca-bca9-050ac6656f03)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome

**Comment by pmjanus** [comment]
![Image](https://github.com/user-attachments/assets/da162540-d39c-45f8-9d5d-f3ed3d8f2750)

When I go to the link I see that arrowhead that lets me expand,  I do not see it on your screenshot but it is not complete so not sure, can you verify this is a bug?
@Viterbo

**Comment by Viterbo** [comment]
> When I go to the link I see that arrowhead that lets me expand, I do not see it on your screenshot but it is not complete so not sure, can you verify this is a bug? @Viterbo

@pmjanus, you're right! I just didn't see the little arrow to expand the code. This is not a bug then. But I wonder If we should do something about it or just leave it as it is...

I will close this issue then. Thnaks
