### ISSUE TITLE
proposal_hash causing msig sign & execute to fail

### ISSUE THREAD

**Issue by rozzaswap** [telosnetwork/open-block-explorer#865]
Using the cleos login option and trying to sign and execute an msig It is a lot more verbose than the last version:

```
cleos -u https://mainnet.telos.net push transaction '{
    "expiration": "2024-07-24T15:41:07",
    "ref_block_num": 0,
    "ref_block_prefix": 0,
    "max_net_usage_words": 0,
    "max_cpu_usage_ms": 0,
    "delay_sec": 0,
    "context_free_actions": [],
    "actions": [
        {
            "account": "eosio.msig",
            "name": "approve",
            "authorization": [
                {
                    "actor": "jt.tcd",
                    "permission": "active"
                }
            ],
            "data": {
                "proposer": "tfpaymentacc",
                "proposal_name": "qdgiqatehlpi",
                "level": {
                    "actor": "jt.tcd",
                    "permission": "active"
                },
                "proposal_hash": null
            },
            "abi": {
                "version": "eosio::abi/1.1",
                "types": [],
                "structs": [],
                "actions": [
                    {
                        "name": "approve",
                        "type": "bytes",
                        "ricardian_contract": ""
                    }
                ],
                "tables": [],
                "ricardian_clauses": [],
                "error_messages": [],
                "abi_extensions": [],
                "variants": [],
                "action_results": []
            }
        }
    ],
    "transaction_extensions": []
}'
```

It seems to be adding "proposal_hash": null which nodeos doesn't like. If we remove this line, it works.

**Comment by pmjanus** [comment]
Jesse - Telos | caleosblocks, [7/28/24 11:12 AM]
Looks like when trying to approve an msig via cleos in OBE the transaction generated is invalid somehow

Jesse - Telos | caleosblocks, [7/28/24 11:13 AM]
This is what was provded in the popup that I copied:


cleos -u https://mainnet.telos.net push transaction '{
    "expiration": "2024-07-28T15:12:00",
    "ref_block_num": 60622,
    "ref_block_prefix": 2647414823,
    "max_net_usage_words": 0,
    "max_cpu_usage_ms": 0,
    "delay_sec": 0,
    "context_free_actions": [],
    "actions": [
        {
            "account": "eosio.msig",
            "name": "approve",
            "authorization": [
                {
                    "actor": "caleosblocks",
                    "permission": "active"
                }
            ],
            "data": {
                "proposer": "jesse.tcd",
                "proposal_name": "hotfix.evm",
                "level": {
                    "actor": "caleosblocks",
                    "permission": "active"
                },
                "proposal_hash": null
            },
            "abi": {
                "version": "eosio::abi/1.1",
                "types": [],
                "structs": [],
                "actions": [
                    {
                        "name": "approve",
                        "type": "bytes",
                        "ricardian_contract": ""
                    }
                ],
                "tables": [],
                "ricardian_clauses": [],
                "error_messages": [],
                "abi_extensions": [],
                "variants": [],
                "action_results": []
            }
        }
    ],
    "transaction_extensions": []
}'

Jesse - Telos | caleosblocks, [7/28/24 11:13 AM]
This is what worked:


cleos -u https://mainnet.telos.net push transaction '{
    "expiration": "2024-07-28T15:12:00",
    "ref_block_num": 60622,
    "ref_block_prefix": 2647414823,
    "max_net_usage_words": 0,
    "max_cpu_usage_ms": 0,
    "delay_sec": 0,
    "context_free_actions": [],
    "actions": [
        {
            "account": "eosio.msig",
            "name": "approve",
            "authorization": [
                {
                    "actor": "caleosblocks",
                    "permission": "active"
                }
            ],
            "data": {
                "proposer": "jesse.tcd",
                "proposal_name": "hotfix.evm",
                "level": {
                    "actor": "caleosblocks",
                    "permission": "active"
                }
            }
        }
    ],
    "transaction_extensions": []
}'

Jesse - Telos | caleosblocks, [7/28/24 11:13 AM]
I removed the ABI as well as the null proposal_hash

Jesse - Telos | caleosblocks, [7/28/24 11:13 AM]
The error I was getting: 


error 2024-07-28T15:11:48.758 thread-0  main.cpp:4498                 operator()           ] Failed with error: Bad Cast (7)
Invalid cast from type 'null_type' to string



Failed to deserialize variant
