### ISSUE TITLE
implement type ahead dropdown for search results 

### ISSUE THREAD

**Issue by DonaldPeat** [telosnetwork/open-block-explorer#88]
**Please describe.**
Using type ahead will reduce guesswork for the user & ensure that the selected entry is a _valid_ search term and/or nav path.

Possible feature would be a toggle to switch typeahead off.

**Describe the solution you'd like**
add ui dropdown element to search bar to display possible search results

**resources**
[https://github.com/darrenjennings/vue-autosuggest] (https://github.com/darrenjennings/vue-autosuggest)
backup option: [https://github.com/pespantelis/vue-typeahead](https://github.com/pespantelis/vue-typeahead)

**Comment by Kersten-TCD** [comment]
Please consider adding feature that automatically selects and opens an account when typeahead only delivers one search result, as implemented in EOS Authority.
