### ISSUE TITLE
Overflow of transaction row / collapse of transaction rows  on Safari not working

### ISSUE THREAD

**Issue by Kersten-TCD** [telosnetwork/open-block-explorer#97]
**Describe the bug**
Display of transactions does not work as expected on Safari. Content in rows overflow to next rows. Same applies to account detail page (same component?)

On transaction detail page, collapse feature does not work either. Adds scroll bar to transaction row instead.

**To Reproduce**

Open [OBE](explorer.telos.net) and view transactions
Click on transaction hash and open transaction details page

**Expected behavior**

**Screenshots**

Homepage:
![Bildschirmfoto 2022-03-15 um 17 12 41](https://user-images.githubusercontent.com/39388424/158426262-7f0a1d30-7039-435f-ad84-d4b7cebeda16.png)

Transaction Details:
![Bildschirmfoto 2022-03-15 um 17 34 24](https://user-images.githubusercontent.com/39388424/158427169-dca3149d-81f3-4b1a-aa56-d29f67a7002b.png)

Account page:
![Bildschirmfoto 2022-03-15 um 17 40 26](https://user-images.githubusercontent.com/39388424/158427930-2f9060a4-e3f1-40ac-8eac-b618a3134623.png)

**Desktop (please complete the following information):**
 - OS: MacOS 12.2.1 
 - Browser Safari
 - Version 15.3

**Comment by karynemayer** [comment]
@Kersten-TCD I haven't been able to reproduce this bug. Would you mind confirming it so we can close this?
